import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import { revalidatePath, revalidateTag } from "next/cache";
import incrementLike from "@/app/actions/actions";
import MobilePostListCategory from "@/app/components/MobileHomepage/MobilePostListCategory";

export const metadata: Metadata = {
  title: "Arhiva Sport - Grude Online",
  description: "Generated by create next app",
};

const Sport = async () => {
  revalidatePath("/sport");
  // let amount = 1;
  // const likes = await incrementLike();
  // console.log(`likes : ${likes}`);

  // const handleIncrement = async () => {
  //   "use server";
  //   await incrementLike(2);
  //   console.log(likes);
  //   revalidateTag("");
  //   // amount += 1;

  //   //revalidateTag("likes");
  // };

  return (
    <div className={styles.postList}>
      <h1 className={styles.headingEdit}>SPORT</h1>
      <Suspense fallback={"Loading Posts..."}>
        <PostList category={"sport"} amount={2} />
      </Suspense>
      {/* <form action={handleIncrement}>
        <button type="submit">Submit</button>
      </form> */}
      <MobilePostListCategory category={"sport"} />
    </div>
  );
};

export default Sport;
