import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import dynamic from "next/dynamic";
const MobilePostListCategory = dynamic(
  () => import("@/app/components/MobileHomepage/MobilePostListCategory"),
  { ssr: false }
);
//import { revalidatePath } from "next/cache";

export const metadata: Metadata = {
  title: "Arhiva Sport - Grude Online",
  description: "Generated by create next app",
};

const Sport = async () => {
  //revalidatePath("/sport");

  return (
    <div className={styles.postList}>
      <h1 className={styles.headingEdit}>SPORT</h1>
      <Suspense fallback={"Loading Posts..."}>
        <PostList category={"sport"} amount={2} />
      </Suspense>
      <MobilePostListCategory category={"sport"} />
    </div>
  );
};

export default Sport;
