import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import dynamic from "next/dynamic";
import Sidebar from "@/app/components/Sidebar/Sidebar";
const MobilePostListCategory = dynamic(
  () => import("@/app/components/MobileHomepage/MobilePostListCategory"),
  { ssr: false }
);
export const metadata: Metadata = {
  title: "Arhiva Sport - Grude Online",
  description: "Generated by create next app",
};
//console.log("asd");

const Sport = async () => {
  return (
    <div className={`${styles.postList} ${styles.grid23}`}>
      <div>
        <h1 className={styles.headingEdit}>SPORT</h1>
        <Suspense fallback={"Loading Posts..."}>
          <PostList category={"sport"} amount={2} />
        </Suspense>
        <MobilePostListCategory category={"sport"} />
      </div>

      <Sidebar />
    </div>
  );
};

export default Sport;
