import { getAllPostsByTags } from "@/app/lib/service";
import { Metadata } from "next";
import React from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import categoryStyles from "../../css/categoryCss/categoryCss.module.css";
import Link from "next/link";
import Image from "next/image";
import defaultImage from "../../../../public/noImage.jpg";
import { formatDateToCroatian } from "@/app/lib/utils";
import { isMobileDevice } from "@/app/lib/deviceCheck";

export const metadata: Metadata = {
  title: "Tags",
  description: "Generated by create next app",
};

const TagDetails = async ({ tag }: { tag: string }) => {
  const data = await getAllPostsByTags(tag);
  const isMobile = isMobileDevice();

  return (
    <div className={styles.postList}>
      <h1 className={styles.headingEdit}>TAG: {tag}</h1>
      <div>
        {data.map((item: any, idx: number) => {
          return (
            <div
              key={idx}
              className={`${categoryStyles.grid2PostList} ${categoryStyles.categoryPaddingBottom}`}
            >
              <Link href={`/${item.slug}`}>
                <div className={styles.relativeEle}>
                  <Image
                    src={
                      item?.featuredImage?.node?.sourceUrl
                        ? item?.featuredImage?.node?.sourceUrl
                        : defaultImage
                    }
                    alt={item.title}
                    sizes="(max-width: 768px) 100vw, 33vw"
                    fill
                    priority={true}
                  />
                  <div className={styles.hoverOverlay}></div>
                </div>
              </Link>

              <div className={categoryStyles.flexCategory}>
                <Link href={`/${item.slug}`}>{item.title}</Link>
                <span>{formatDateToCroatian(item?.date)}</span>
                {!isMobile && (
                  <div
                    dangerouslySetInnerHTML={{
                      __html: item?.content.slice(0, 200) + " ...",
                    }}
                  ></div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default TagDetails;
