import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import MobilePostListCategory from "@/app/components/MobileHomepage/MobilePostListCategory";
//import { revalidatePath } from "next/cache";

export const metadata: Metadata = {
  title: "Arhiva Zanimljivosti - Grude Online",
  description: "Generated by create next app",
};

const Zanimljivosti = async () => {
  //revalidatePath("/gospodarstvo");
  return (
    <div className={styles.postList}>
      <h1 className={styles.headingEdit}>ZANIMLJIVOSTI</h1>
      <Suspense>
        <PostList category={"zanimljivosti"} amount={2} />
      </Suspense>
      <MobilePostListCategory category={"zanimljivosti"} />
    </div>
  );
};

export default Zanimljivosti;
