import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import MobilePostListCategory from "@/app/components/MobileHomepage/MobilePostListCategory";
import Sidebar from "@/app/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Arhiva Zanimljivosti - Grude Online",
  description: "Generated by create next app",
};

const Zanimljivosti = async () => {
  return (
    <div className={`${styles.postList} ${styles.grid23}`}>
      <div>
        <h1 className={styles.headingEdit}>ZANIMLJIVOSTI</h1>
        <Suspense>
          <PostList category={"zanimljivosti"} amount={2} />
        </Suspense>
        <MobilePostListCategory category={"zanimljivosti"} />
      </div>
      <Sidebar />
    </div>
  );
};

export default Zanimljivosti;
