import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import MobilePostListCategory from "@/app/components/MobileHomepage/MobilePostListCategory";
import Sidebar from "@/app/components/Sidebar/Sidebar";
//import { revalidatePath } from "next/cache";

export const metadata: Metadata = {
  title: "Arhiva Grude Online - Grude Online",
  description: "Generated by create next app",
};

const GrudeOnline = () => {
  return (
    <div className={`${styles.postList} ${styles.grid23}`}>
      <div>
        <h1 className={styles.headingEdit}>GRUDE ONLINE</h1>
        <Suspense>
          <PostList category={"grude-online"} amount={2} />
        </Suspense>
        <MobilePostListCategory category={"grude-online"} />
      </div>
      <Sidebar />
    </div>
  );
};

export default GrudeOnline;
