import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./css/mainCss/mainStyle.module.css";
import FooterComponent from "./components/Footer/FooterComponent";
import "@fortawesome/fontawesome-free/css/all.css";
import { Suspense } from "react";
import dynamic from "next/dynamic";
//import NaslovneVijesti from "./components/NaslovneVijesti/NaslovneVijesti";
const NaslovneVijesti = dynamic(
  () => import("./components/NaslovneVijesti/NaslovneVijesti"),
  { ssr: false }
);
const Navbar = dynamic(() => import("./components/Nav/Navbar"), { ssr: false });
//import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={`${inter.className} ${styles.styleContainer}`}>
        <Navbar />
        <div className={styles.container}>
          <div>{children}</div>
        </div>
        <FooterComponent />
      </body>
    </html>
  );
}
