import PostList from "@/app/components/PostList/PostList";
import { Metadata } from "next";
import React, { Suspense } from "react";
import styles from "../../css/mainCss/mainStyle.module.css";
import MobilePostListCategory from "@/app/components/MobileHomepage/MobilePostListCategory";
import Sidebar from "@/app/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Arhiva Gospodarstvo - Grude Online",
  description: "Generated by create next app",
};

const Gospodarstvo = async () => {
  return (
    <div className={`${styles.postList} ${styles.grid23}`}>
      <div>
        <h1 className={styles.headingEdit}>
          {" "}
          <span
            style={{
              borderBottom: "1px solid darkslateblue",
              paddingBottom: "5px",
            }}
          >
            GOSPODARSTVO
          </span>
        </h1>
        <Suspense>
          <PostList category={"gospodarstvo"} amount={2} />
        </Suspense>
        <MobilePostListCategory category={"gospodarstvo"} />
      </div>
      <Sidebar />
    </div>
  );
};

export default Gospodarstvo;
